version: '3.4'

services:

  trongmongodb:
    image: choudang/mongodb:trong
    ports:
        - "27017:27017"
    networks:
        - custom_network

  #productdb:
  #  container_name: productdb
  #  restart: always
  #  ports:
  #      - "27017:27017"
  #  volumes:
  #      - mongo_data:/data/db 

  customer.microservice:
    container_name: customer-api
    image: choudang/customermicroservice
    build:
      context: .
      dockerfile: Customer.Microservice/Dockerfile
    environment:
        MONGO_URL: mongodb://172.19.0.2:27017
    ports:
        - "4201:80"
    networks:
        - custom_network

  product.microservice:
    container_name: product-api
    image: choudang/productmicroservice
    build:
      context: .
      dockerfile: Product.Microservice/Dockerfile
    environment:
        MONGO_URL: mongodb://172.19.0.2:27017
    ports:
       - "4202:80"
    networks:
        - custom_network

  gateway.api:
    image: choudang/gatewayapi
    build:
      context: .
      dockerfile: Gateway.API/Dockerfile
    ports:
    - "3002:80"
    networks:
        - custom_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5673:5672
      - 8080:15672
    networks:
       - custom_network

networks:
  custom_network:
    driver: bridge