name: CI/CD with Multiple Dockerfiles

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push Docker images Customer
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./MicroServices/Customer.MicroService
          file: ./MicroServices/Customer.MicroService/Dockerfile
          target: build  # Replace 'build' with your specific build target if applicable
          load: true
          push: true
      -
        name: Build and push Docker images Customer
        id: docker_build_2
        uses: docker/build-push-action@v5
        with:
          context: ./MicroServices/Product.MicroService
          file: ./MicroServices/Product.MicroService/Dockerfile
          target: build  # Replace 'build' with your specific build target if applicable
          load: true
          push: true
      -
        name: Build and push Docker images Customer
        id: docker_build_3
        uses: docker/build-push-action@v5
        with:
          context: ./Gateway.API
          file: ./Gateway.API/Dockerfile
          target: build  # Replace 'build' with your specific build target if applicable
          load: true
          push: true    
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/micro-gateway:latest
