name: CI/CD with Multiple Dockerfiles

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Set up Docker Compose CLI
        uses: docker/compose-cli@v1

      - name: Build and push Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Push Docker images
        run: docker-compose -f docker-compose.yml push

      - name: Deploy using Docker Compose
        run: docker-compose -f docker-compose.yml up -d
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/micro-gateway:latest
